version: '3'

services:
  docker-server:
    build: .docker/docker
    image: docker-server
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=superAdmin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached
    restart: always

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - docker-server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8383:80
    links:
      - "mysql:mysql"
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root